kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: postgres15-cron
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'postgres15-cron:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/bolyachevets/business-db-sync.git'
      ref: main
  triggers:
    - type: ConfigChange
  runPolicy: Serial
